In [6]:
#Third party imports

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px

In [7]:
#Load csv files into dataframes

df1 = pd.read_csv("mexico-real-estate-1.csv")
df2 = pd.read_csv("mexico-real-estate-2.csv")
df3 = pd.read_csv("mexico-real-estate-3.csv")

In [ ]:
# Get summary information for df1 (Data types, memory, non-null counts)
# Get shape for df1 (Rows, Columns)
# Get head for df1 (first 5 rows)

print(df1.info()); print( df1.shape)
df1.head()

<class 'pandas.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   property_type  700 non-null    str
 1   state          700 non-null    str
 2   lat            583 non-null    float64
 3   lon            583 non-null    float64
 4   area_m2        700 non-null    float64
 5   price_usd      700 non-null    str
dtypes: float64(3), str(3)
memory usage: 32.9 KB
None
(700, 6)

,property_type,state,lat,lon,area_m2,price_usd
0,house,Estado de México,19.560181,-99.233528,150.0,"$67,965.56"
1,house,Nuevo León,25.688436,-100.198807,186.0,"$63,223.78"
2,apartment,Guerrero,16.767704,-99.764383,82.0,"$84,298.37"
3,apartment,Guerrero,16.829782,-99.911012,150.0,"$94,308.80"
4,house,Veracruz de Ignacio de la Llave,NaN,NaN,175.0,"$94,835.67"

In [10]:
# Get summary information for df2 (data types, memory, non-null counts)
# Get shape for df2 (Rows, Columns)
# Get head for df2 (First 5 rows)

print(df2.info()); print(df2.shape)
df2.head()

<class 'pandas.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   property_type  700 non-null    str
 1   state          700 non-null    str
 2   lat            571 non-null    float64
 3   lon            571 non-null    float64
 4   area_m2        700 non-null    float64
 5   price_mxn      700 non-null    float64
dtypes: float64(4), str(2)
memory usage: 32.9 KB
None
(700, 6)

  property_type       state        lat         lon  area_m2  price_mxn
0     apartment  Nuevo León  25.721081 -100.345581     72.0  1300000.0
1     apartment      Puebla        NaN         NaN    190.0  2500000.0
2         house     Morelos  23.634501 -102.552788    360.0  5300000.0
3         house     Morelos        NaN         NaN     76.0   820000.0
4         house      Puebla        NaN         NaN    200.0  1100000.0

In [11]:
# Get summary information for df3 (data types, memory, non-null count)
# Get shape of df3 (Rows, Columns)
# Get head for df3 (First 5 rows)

print(df3.info()); print(df3.shape)
df3.head()

<class 'pandas.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 5 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   property_type            700 non-null    str
 1   place_with_parent_names  700 non-null    str
 2   lat-lon                  582 non-null    str
 3   area_m2                  700 non-null    float64
 4   price_usd                700 non-null    float64
dtypes: float64(2), str(3)
memory usage: 27.5 KB
None
(700, 5)

,property_type,place_with_parent_names,lat-lon,area_m2,price_usd
0,apartment,|México|Distrito Federal|Gustavo A. Madero|Acu...,"19.52589,-99.151703",71.0,48550.59
1,house,|México|Estado de México|Toluca|Metepec|,"19.2640539,-99.5727534",233.0,168636.73
2,house,|México|Estado de México|Toluca|Toluca de Lerd...,"19.268629,-99.671722",300.0,86932.69
3,house,|México|Morelos|Temixco|Burgos Bugambilias|,NaN,275.0,263432.41
4,apartment,|México|Veracruz de Ignacio de la Llave|Veracruz|,"19.511938,-96.871956",84.0,68508.67

In [14]:
# Remove `NaN` values from the df1 dataset
df1.dropna(inplace=True)

In [15]:
# Remove dollar sign and comma from `price usd` 
# Convert the values from string to float type

df1["price_usd"] = (df1["price_usd"]
                    .str.replace("$", "", regex=False)
                    .str.replace(",", "")
                    .astype(float)
                    )

In [16]:
#Confirm that the new dataframe has no null values and the right data types

print(df1.info()); print(df1.shape)
df1.head()

<class 'pandas.DataFrame'>
Index: 583 entries, 0 to 699
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   property_type  583 non-null    str
 1   state          583 non-null    str
 2   lat            583 non-null    float64
 3   lon            583 non-null    float64
 4   area_m2        583 non-null    float64
 5   price_usd      583 non-null    float64
dtypes: float64(4), str(2)
memory usage: 31.9 KB
None
(583, 6)

  property_type             state        lat         lon  area_m2  price_usd
0         house  Estado de México  19.560181  -99.233528    150.0   67965.56
1         house        Nuevo León  25.688436 -100.198807    186.0   63223.78
2     apartment          Guerrero  16.767704  -99.764383     82.0   84298.37
3     apartment          Guerrero  16.829782  -99.911012    150.0   94308.80
5         house           Yucatán  21.052583  -89.538639    205.0  105191.37

In [18]:
# Drop `NaN` values from df2
df2.dropna(inplace=True)

In [19]:
# Create `price_usd` column by converting the currency from pesos to USD
# Round result to 2 decimal places
# One dollar is 19 mexican pesos

df2["price_usd"] = (df2["price_mxn"] / 19).round(2)

In [21]:
# Drop `price_mxn` column

df2.drop(columns=["price_mxn"], inplace=True)

In [22]:
# Confirm that the new dataframe has the right columns and no null values

df2.head()

  property_type             state        lat         lon  area_m2  price_usd
0     apartment        Nuevo León  25.721081 -100.345581     72.0   68421.05
2         house           Morelos  23.634501 -102.552788    360.0  278947.37
6     apartment  Estado de México  19.272040  -99.572013     85.0   65789.47
7         house   San Luis Potosí  22.138882 -100.996510    158.0  111578.95
8     apartment  Distrito Federal  19.394558  -99.129707     65.0   39904.74

In [27]:
df3.head()

,property_type,place_with_parent_names,lat-lon,area_m2,price_usd
0,apartment,|México|Distrito Federal|Gustavo A. Madero|Acu...,"19.52589,-99.151703",71.0,48550.59
1,house,|México|Estado de México|Toluca|Metepec|,"19.2640539,-99.5727534",233.0,168636.73
2,house,|México|Estado de México|Toluca|Toluca de Lerd...,"19.268629,-99.671722",300.0,86932.69
3,house,|México|Morelos|Temixco|Burgos Bugambilias|,NaN,275.0,263432.41
4,apartment,|México|Veracruz de Ignacio de la Llave|Veracruz|,"19.511938,-96.871956",84.0,68508.67

In [ ]:
# Split the `"lat-lon"` column into "lat" and "lon"
df3[["lat", "lon"]] = (
    df3["lat-lon"]
    .str.split(",", expand=True)
    .astype(float))

In [32]:
# Create a state column from `place_with_parent_names` by splitting it

df3["state"] = (
    df3["place_with_parent_names"]
    .str.split("|", expand=True)[2]
)

In [37]:
# Drop `lat-lon` and `place_with_parent_names` columns

df3.drop(columns=["lat-lon", "place_with_parent_names"], inplace=True)

In [38]:
# Drop `NaN` values
df3.dropna(inplace=True)

In [ ]:
# Confirm dataframe has the right column names and no null values
df3.head()

,property_type,area_m2,price_usd,lat,lon,state
0,apartment,71.0,48550.59,19.525890,-99.151703,Distrito Federal
1,house,233.0,168636.73,19.264054,-99.572753,Estado de México
2,house,300.0,86932.69,19.268629,-99.671722,Estado de México
4,apartment,84.0,68508.67,19.511938,-96.871956,Veracruz de Ignacio de la Llave
5,house,175.0,102763.00,20.689157,-103.366728,Jalisco